name: Daily Flight Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # runs at midnight UTC (adjust as needed)
  workflow_dispatch:     # manual trigger option

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add flight_data.csv
          if ! git diff --quiet; then
            git commit -m "Automated flight data update"
            git push
          else
            echo "No changes to commit"
          fi
